### ISSUE TITLE
Would it be possible to record multiple values?

### ISSUE THREAD

**Issue by xeoncross** [aFarkas/remote-list#1]
I would like to have multiple suggestions divided by commas or perhaps in a hidden input.

**Comment by aFarkas** [comment]
I'm not sure what you mean here. Do you mean something like this:
http://afarkas.github.io/webshim/demos/demos/cfgs/list-datalist.html#type=email&list=contacts&multiple=on
or 
http://afarkas.github.io/webshim/demos/demos/cfgs/list-datalist.html#type=search&list=state-list&multiple=on&multiple=on

Simply type a suggestion + a , into a field and it adds new suggestions instead of overriding those?

**Comment by aFarkas** [comment]
Please re-open, if you need something else.
